### ISSUE TITLE
Hacktoberfest 2021: Program with emojis 😲 

### ISSUE THREAD

**Issue by spenserblack** [spenserblack/emoji-getter#4]
This is a project written in [EmojiCode](https://www.emojicode.org/), a language that uses emojis for syntax. By contributing to this project, you can brag that you know how to program with emojis :100:

What we need most is more emojis. *Many more emojis.*
To add an emoji, you will need to add a name for the emoji, the emoji itself, and some keywords for the emoji.

For more information, please consult [`CONTRIBUTING.md`](https://github.com/spenserblack/emoji-getter/blob/master/CONTRIBUTING.md).

Of course, other contributions are also welcome 😃 

Happy Hacking! 🎃

**Comment by gaayatri25** [comment]
Hello, can I work on this?
