### ISSUE TITLE
Hacktoberfest 2021: Learn to program with emojis :tada:

### ISSUE THREAD

**Issue by spenserblack** [spenserblack/emoji-getter#5]
This is a project written in [EmojiCode](https://www.emojicode.org/), a language that uses emojis for syntax. By contributing to this project, you can brag that you know how to program with emojis :100:

What we need most is more emojis. *Many more emojis.* You don't have to add *all the emojis* of course. Even only 1 new emoji is a welcome contribution :smiley:
To add an emoji, you will need to add a name for the emoji, the emoji itself, and some keywords for the emoji.

For more information, please consult [`CONTRIBUTING.md`](https://github.com/spenserblack/emoji-getter/blob/master/CONTRIBUTING.md).

Of course, other contributions are also welcome 😃 

Happy Hacking! 🎃

**Comment by ok524** [comment]
Very interesting language! Let me try!
